version: 0.2.0.{build}
configuration: Release
init:
- cmd: if "%APPVEYOR_REPO_TAG%" NEQ "true" set BUILD_QUALITY=-unstable
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(SEMVER)
  assembly_file_version: $(SEMVER).{build}
  assembly_informational_version: $(SEMVER)$(BUILD_QUALITY)
environment:
  SEMVER: 0.2.0
install:
- cmd: tools\nuget.exe restore
build:
  publish_nuget: true
  verbosity: minimal
after_build:
- cmd: tools\7za.exe a -tzip Kyrodan.HiDriveSDK.%SEMVER%%BUILD_QUALITY%.zip .\src\Kyrodan.HiDrive\bin\%configuration%\*.*
artifacts:
- path: Kyrodan.HiDriveSDK.*.zip
  name: ZIP-Distribution
deploy:
- provider: NuGet
  api_key:
    secure: sGR4t0DGDW9V8uCS3wkQS/is2NnGc+pizHdfDBocXxuoDUIPQIxt6O4FanfPqTuG
  skip_symbols: false
  on:
    branch: master
    appveyor_repo_tag: true
- provider: GitHub
  auth_token:
    secure: zqGFJdh0d0e+S2Eyudc4gCjQqImkQutu/TsN9knDXJCXMaVl8izm9vnMK9ayX7VP
  artifact: Kyrodan.HiDriveSDK.*.zip
  draft: true
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
